// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./banner.client";

export const source = "'use client';\n\nimport { IconInfoCircle } from '@tabler/icons-react';\n\nimport {\n  Alert,\n  AlertDescription,\n  AlertIcon,\n  AlertTitle,\n} from '@/components/alert/alert';\n\nexport default function AlertBanner() {\n  return (\n    <div className=\"nx:w-full nx:max-w-lg nx:overflow-hidden nx:rounded-md nx:border nx:border-border-default\">\n      <Alert presentation=\"banner\" variant=\"information\">\n        <AlertIcon>\n          <IconInfoCircle />\n        </AlertIcon>\n        <AlertTitle>Scheduled maintenance</AlertTitle>\n        <AlertDescription>\n          The dashboard is read-only on Sunday from 02:00 to 04:00 UTC.\n        </AlertDescription>\n      </Alert>\n      <div className=\"nx:h-24 nx:bg-background\" />\n    </div>\n  );\n}\n";
