// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./demo.client";

export const source = "'use client';\n\nimport { IconInfoCircle } from '@tabler/icons-react';\n\nimport {\n  Alert,\n  AlertDescription,\n  AlertIcon,\n  AlertTitle,\n} from '@/components/alert/alert';\n\nexport default function AlertDemo() {\n  return (\n    <Alert className=\"nx:max-w-md\">\n      <AlertIcon>\n        <IconInfoCircle />\n      </AlertIcon>\n      <AlertTitle>Heads up!</AlertTitle>\n      <AlertDescription>\n        You can add components and dependencies to your app using the CLI.\n      </AlertDescription>\n    </Alert>\n  );\n}\n";
