// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./with-actions.client";

export const source = "'use client';\n\nimport { IconAlertTriangle } from '@tabler/icons-react';\n\nimport {\n  Alert,\n  AlertActions,\n  AlertContent,\n  AlertDescription,\n  AlertIcon,\n  AlertTitle,\n} from '@/components/alert/alert';\nimport { Button } from '@/components/button/button';\n\nexport default function AlertWithActions() {\n  return (\n    <Alert variant=\"warning\" className=\"nx:max-w-md\">\n      <AlertIcon>\n        <IconAlertTriangle />\n      </AlertIcon>\n      <AlertContent>\n        <AlertTitle>Plan limit reached</AlertTitle>\n        <AlertDescription>\n          Upgrade the workspace or remove unused seats before inviting more\n          members.\n        </AlertDescription>\n      </AlertContent>\n      <AlertActions>\n        <Button>Upgrade</Button>\n        <Button variant=\"outline\">View usage</Button>\n      </AlertActions>\n    </Alert>\n  );\n}\n";
