[mcp_servers.chrome-devtools]
command = "npx"
args = [
    "chrome-devtools-mcp@latest",
    "--executable-path=/Applications/Brave Browser.app/Contents/MacOS/Brave Browser",
]

[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"

[mcp_servers.nexus-docs-mcp]
url = "http://localhost:6282/sse"
