// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./disabled.client";

export const source = "'use client';\n\nimport {\n  Accordion,\n  AccordionContent,\n  AccordionItem,\n  AccordionTrigger,\n} from '@/components/accordion/accordion';\n\nexport default function AccordionDisabled() {\n  return (\n    <Accordion type=\"single\" collapsible className=\"nx:max-w-md\">\n      <AccordionItem value=\"plan\">\n        <AccordionTrigger>Current plan</AccordionTrigger>\n        <AccordionContent>You are on the Team plan.</AccordionContent>\n      </AccordionItem>\n      <AccordionItem value=\"enterprise\" disabled>\n        <AccordionTrigger>Enterprise features</AccordionTrigger>\n        <AccordionContent>Available on the Enterprise plan.</AccordionContent>\n      </AccordionItem>\n    </Accordion>\n  );\n}\n";
