// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./demo.client";

export const source = "'use client';\n\nimport {\n  Select,\n  SelectContent,\n  SelectItem,\n  SelectTrigger,\n  SelectValue,\n} from '@/components/select/select';\n\nexport default function SelectDemo() {\n  return (\n    <Select>\n      <SelectTrigger className=\"nx:w-[180px]\" aria-label=\"Fruit\">\n        <SelectValue placeholder=\"Select a fruit\" />\n      </SelectTrigger>\n      <SelectContent>\n        <SelectItem value=\"apple\">Apple</SelectItem>\n        <SelectItem value=\"banana\">Banana</SelectItem>\n        <SelectItem value=\"orange\">Orange</SelectItem>\n        <SelectItem value=\"grape\">Grape</SelectItem>\n        <SelectItem value=\"mango\">Mango</SelectItem>\n      </SelectContent>\n    </Select>\n  );\n}\n";
