// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./invalid.client";

export const source = "'use client';\n\nimport {\n  Select,\n  SelectContent,\n  SelectItem,\n  SelectTrigger,\n  SelectValue,\n} from '@/components/select/select';\n\nexport default function SelectInvalid() {\n  return (\n    <div className=\"nx:grid nx:w-[180px] nx:gap-1.5\">\n      <Select>\n        <SelectTrigger\n          aria-label=\"Region\"\n          aria-invalid\n          aria-describedby=\"select-invalid-region-error\"\n        >\n          <SelectValue placeholder=\"Select a region\" />\n        </SelectTrigger>\n        <SelectContent>\n          <SelectItem value=\"us-east\">US East</SelectItem>\n          <SelectItem value=\"eu-west\">EU West</SelectItem>\n          <SelectItem value=\"ap-south\">AP South</SelectItem>\n        </SelectContent>\n      </Select>\n      <p\n        id=\"select-invalid-region-error\"\n        className=\"nx:typography-body-small nx:text-error-subtle-foreground\"\n      >\n        Choose a region to deploy to.\n      </p>\n    </div>\n  );\n}\n";
