// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./invalid.client";

export const source = "'use client';\n\nimport {\n  Select,\n  SelectContent,\n  SelectItem,\n  SelectTrigger,\n  SelectValue,\n} from '@/components/select/select';\n\nexport default function SelectInvalid() {\n  return (\n    <Select>\n      <SelectTrigger className=\"nx:w-[180px]\" aria-label=\"Region\" aria-invalid>\n        <SelectValue placeholder=\"Select a region\" />\n      </SelectTrigger>\n      <SelectContent>\n        <SelectItem value=\"us-east\">US East</SelectItem>\n        <SelectItem value=\"eu-west\">EU West</SelectItem>\n        <SelectItem value=\"ap-south\">AP South</SelectItem>\n      </SelectContent>\n    </Select>\n  );\n}\n";
