// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./demo.client";

export const source = "'use client';\n\nimport { IconFileTypePdf, IconX } from '@tabler/icons-react';\n\nimport {\n  Attachment,\n  AttachmentActions,\n  AttachmentContent,\n  AttachmentDescription,\n  AttachmentMedia,\n  AttachmentTitle,\n} from '@/components/attachment/attachment';\nimport { Button } from '@/components/button/button';\n\nexport default function AttachmentDemo() {\n  return (\n    <Attachment className=\"nx:w-80\">\n      <AttachmentMedia variant=\"icon\">\n        <IconFileTypePdf />\n      </AttachmentMedia>\n      <AttachmentContent>\n        <AttachmentTitle>report.pdf</AttachmentTitle>\n        <AttachmentDescription>2.4 MB</AttachmentDescription>\n      </AttachmentContent>\n      <AttachmentActions>\n        <Button variant=\"ghost\" size=\"icon-sm\" aria-label=\"Remove report.pdf\">\n          <IconX />\n        </Button>\n      </AttachmentActions>\n    </Attachment>\n  );\n}\n";
