// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./badge-demo.client";

export const source = "import { Badge } from '@nexus_ds/react';\n\nexport default function BadgeDemo() {\n  return <Badge>Badge</Badge>;\n}\n";
