// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { default as Component } from '../../examples/badge-demo';

export const source = "'use client';\n\nimport { Badge } from '@nexus_ds/react';\n\nexport default function BadgeDemo() {\n  return <Badge>Badge</Badge>;\n}\n";
