// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { default as Component } from '../../examples/button-variants';

export const source = "'use client';\n\nimport { Button } from '@nexus_ds/react';\n\nexport default function ButtonVariants() {\n  return (\n    <div className=\"nx:flex nx:flex-wrap nx:items-center nx:gap-2\">\n      <Button variant=\"default\">Default</Button>\n      <Button variant=\"secondary\">Secondary</Button>\n      <Button variant=\"outline\">Outline</Button>\n      <Button variant=\"ghost\">Ghost</Button>\n      <Button variant=\"destructive\">Destructive</Button>\n      <Button variant=\"link\">Link</Button>\n    </div>\n  );\n}\n";
