// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./button-core-variants.client";

export const source = "import { Button } from '@nexus_ds/react';\n\nexport default function ButtonCoreVariants() {\n  return (\n    <div className=\"nx:flex nx:flex-wrap nx:gap-3\">\n      <Button>Primary</Button>\n      <Button variant=\"secondary\">Secondary</Button>\n      <Button variant=\"outline\">Outline</Button>\n      <Button variant=\"ghost\">Ghost</Button>\n    </div>\n  );\n}\n";
