// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { default as Component } from "../../examples/button-demo";

export const source = "'use client';\n\nimport { Button } from '@nexus_ds/react';\n\nexport default function ButtonDemo() {\n  return <Button>Button</Button>;\n}\n";
