/**
 * CLI-specific error codes
 */
export const CLIErrorCode = {
  // Configuration errors
  CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND',
  CONFIG_INVALID: 'CONFIG_INVALID',
  CONFIG_WRITE_FAILED: 'CONFIG_WRITE_FAILED',

  // Authentication errors
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_EXPIRED: 'AUTH_EXPIRED',

  // Registry errors
  REGISTRY_UNREACHABLE: 'REGISTRY_UNREACHABLE',
  REGISTRY_TIMEOUT: 'REGISTRY_TIMEOUT',
  REGISTRY_ERROR: 'REGISTRY_ERROR',
  COMPONENT_NOT_FOUND: 'COMPONENT_NOT_FOUND',
  VERSION_NOT_FOUND: 'VERSION_NOT_FOUND',

  // File system errors
  FILE_READ_FAILED: 'FILE_READ_FAILED',
  FILE_WRITE_FAILED: 'FILE_WRITE_FAILED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_ALREADY_EXISTS: 'FILE_ALREADY_EXISTS',
  DIRECTORY_CREATE_FAILED: 'DIRECTORY_CREATE_FAILED',

  // Merge errors
  MERGE_CONFLICT: 'MERGE_CONFLICT',
  MERGE_FAILED: 'MERGE_FAILED',

  // Dependency errors
  CIRCULAR_DEPENDENCY: 'CIRCULAR_DEPENDENCY',
  MISSING_DEPENDENCY: 'MISSING_DEPENDENCY',

  // Validation errors
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_INPUT: 'INVALID_INPUT',

  // General errors
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type CLIErrorCode = (typeof CLIErrorCode)[keyof typeof CLIErrorCode];
