// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./demo.client";

export const source = "'use client';\n\nimport {\n  Carousel,\n  CarouselContent,\n  CarouselItem,\n  CarouselNext,\n  CarouselPrevious,\n} from '@/components/carousel/carousel';\n\nconst slides = [1, 2, 3, 4, 5];\n\nexport default function CarouselDemo() {\n  return (\n    <div className=\"nx:w-full nx:max-w-xs nx:px-12\">\n      <Carousel className=\"nx:w-full\" aria-label=\"Numbered slides\">\n        <CarouselContent>\n          {slides.map((slide) => (\n            <CarouselItem\n              key={slide}\n              aria-label={`Slide ${slide} of ${slides.length}`}\n            >\n              <div className=\"nx:flex nx:aspect-square nx:items-center nx:justify-center nx:rounded-md nx:border-default nx:border-border-default nx:typography-heading-large\">\n                {slide}\n              </div>\n            </CarouselItem>\n          ))}\n        </CarouselContent>\n        <CarouselPrevious />\n        <CarouselNext />\n      </Carousel>\n    </div>\n  );\n}\n";
