// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./content-only.client";

export const source = "'use client';\n\nimport { Card, CardContent } from '@/components/card/card';\n\nexport default function CardContentOnly() {\n  return (\n    <Card className=\"nx:w-full nx:max-w-sm\">\n      <CardContent className=\"nx:pt-6\">\n        <p className=\"nx:typography-body-default\">\n          A card with only content works as a plain surface for a note, a quote,\n          or a single metric.\n        </p>\n      </CardContent>\n    </Card>\n  );\n}\n";
