// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./demo.client";

export const source = "'use client';\n\nimport { Button } from '@/components/button/button';\nimport {\n  Card,\n  CardContent,\n  CardDescription,\n  CardFooter,\n  CardHeader,\n  CardTitle,\n} from '@/components/card/card';\n\nexport default function CardDemo() {\n  return (\n    <Card className=\"nx:w-full nx:max-w-sm\">\n      <CardHeader>\n        <CardTitle asChild>\n          <h2>Deploy to production</h2>\n        </CardTitle>\n        <CardDescription>\n          Ship the latest build of the main branch.\n        </CardDescription>\n      </CardHeader>\n      <CardContent>\n        <p className=\"nx:typography-body-default\">\n          12 commits since the last release, all checks passing.\n        </p>\n      </CardContent>\n      <CardFooter>\n        <Button variant=\"outline\">Review changes</Button>\n        <Button>Deploy</Button>\n      </CardFooter>\n    </Card>\n  );\n}\n";
