// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./footer-actions.client";

export const source = "'use client';\n\nimport { Button } from '@/components/button/button';\nimport {\n  Card,\n  CardContent,\n  CardDescription,\n  CardFooter,\n  CardHeader,\n  CardTitle,\n} from '@/components/card/card';\n\nexport default function CardFooterActions() {\n  return (\n    <Card className=\"nx:w-full nx:max-w-sm\">\n      <CardHeader>\n        <CardTitle>Email notifications</CardTitle>\n        <CardDescription>Choose what lands in your inbox.</CardDescription>\n      </CardHeader>\n      <CardContent>\n        <p className=\"nx:typography-body-default\">\n          You will get a daily digest of mentions and assigned issues.\n        </p>\n      </CardContent>\n      <CardFooter className=\"nx:justify-end\">\n        <Button variant=\"outline\">Cancel</Button>\n        <Button>Save preferences</Button>\n      </CardFooter>\n    </Card>\n  );\n}\n";
