// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./header-with-action.client";

export const source = "'use client';\n\nimport { Button } from '@/components/button/button';\nimport {\n  Card,\n  CardAction,\n  CardContent,\n  CardDescription,\n  CardHeader,\n  CardTitle,\n} from '@/components/card/card';\n\nexport default function CardHeaderWithAction() {\n  return (\n    <Card className=\"nx:w-full nx:max-w-sm\">\n      <CardHeader>\n        <CardTitle asChild>\n          <h4>Team members</h4>\n        </CardTitle>\n        <CardDescription>Invite people to collaborate.</CardDescription>\n        <CardAction>\n          <Button size=\"sm\" variant=\"outline\">\n            Invite\n          </Button>\n        </CardAction>\n      </CardHeader>\n      <CardContent>\n        <p className=\"nx:typography-body-default\">\n          4 of 5 seats in use on the Team plan.\n        </p>\n      </CardContent>\n    </Card>\n  );\n}\n";
