// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./variants.client";

export const source = "'use client';\n\nimport { Bubble, BubbleContent, BubbleGroup } from '@/components/bubble/bubble';\n\nexport default function BubbleVariants() {\n  return (\n    <BubbleGroup className=\"nx:w-full nx:max-w-sm\">\n      <Bubble variant=\"muted\">\n        <BubbleContent>Muted is the default incoming surface.</BubbleContent>\n      </Bubble>\n      <Bubble variant=\"primary\" align=\"end\">\n        <BubbleContent>Primary marks your own messages.</BubbleContent>\n      </Bubble>\n      <Bubble variant=\"outline\">\n        <BubbleContent>Outline keeps the turn quiet.</BubbleContent>\n      </Bubble>\n      <Bubble variant=\"ghost\">\n        <BubbleContent>Ghost drops the surface entirely.</BubbleContent>\n      </Bubble>\n      <Bubble variant=\"destructive\">\n        <BubbleContent>Destructive flags a failed turn.</BubbleContent>\n      </Bubble>\n    </BubbleGroup>\n  );\n}\n";
