// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./with-reactions.client";

export const source = "'use client';\n\nimport {\n  Bubble,\n  BubbleContent,\n  BubbleGroup,\n  BubbleReactions,\n} from '@/components/bubble/bubble';\n\nexport default function BubbleWithReactions() {\n  return (\n    <BubbleGroup className=\"nx:w-full nx:max-w-sm\">\n      <Bubble align=\"start\">\n        <BubbleContent>Landed the marker primitive.</BubbleContent>\n        <BubbleReactions>🎉 3</BubbleReactions>\n      </Bubble>\n      <Bubble variant=\"primary\" align=\"end\">\n        <BubbleContent>Reviewing it now.</BubbleContent>\n        <BubbleReactions align=\"start\">👀 1</BubbleReactions>\n      </Bubble>\n    </BubbleGroup>\n  );\n}\n";
