// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./checked.client";

export const source = "'use client';\n\nimport { Label } from '@/components/label/label';\nimport { Switch } from '@/components/switch/switch';\n\nexport default function SwitchChecked() {\n  return (\n    <div className=\"nx:flex nx:flex-col nx:gap-3\">\n      <div className=\"nx:flex nx:items-center nx:gap-2\">\n        <Switch id=\"switch-checked-wifi\" />\n        <Label htmlFor=\"switch-checked-wifi\">Wi-Fi</Label>\n      </div>\n      <div className=\"nx:flex nx:items-center nx:gap-2\">\n        <Switch id=\"switch-checked-bluetooth\" defaultChecked />\n        <Label htmlFor=\"switch-checked-bluetooth\">Bluetooth</Label>\n      </div>\n    </div>\n  );\n}\n";
