// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./checked.client";

export const source = "'use client';\n\nimport { Switch } from '@/components/switch/switch';\n\nexport default function SwitchChecked() {\n  return (\n    <div className=\"nx:flex nx:flex-col nx:gap-3\">\n      <div className=\"nx:flex nx:items-center nx:gap-2\">\n        <Switch id=\"switch-checked-off\" />\n        <label\n          htmlFor=\"switch-checked-off\"\n          className=\"nx:typography-label-default\"\n        >\n          Off\n        </label>\n      </div>\n      <div className=\"nx:flex nx:items-center nx:gap-2\">\n        <Switch id=\"switch-checked-on\" defaultChecked />\n        <label\n          htmlFor=\"switch-checked-on\"\n          className=\"nx:typography-label-default\"\n        >\n          On\n        </label>\n      </div>\n    </div>\n  );\n}\n";
