// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./demo.client";

export const source = "'use client';\n\nimport { Switch } from '@/components/switch/switch';\n\nexport default function SwitchDemo() {\n  return (\n    <div className=\"nx:flex nx:items-center nx:gap-2\">\n      <Switch id=\"switch-demo-airplane\" />\n      <label\n        htmlFor=\"switch-demo-airplane\"\n        className=\"nx:typography-label-default\"\n      >\n        Airplane mode\n      </label>\n    </div>\n  );\n}\n";
