// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./demo.client";

export const source = "'use client';\n\nimport { Label } from '@/components/label/label';\nimport { Switch } from '@/components/switch/switch';\n\nexport default function SwitchDemo() {\n  return (\n    <div className=\"nx:flex nx:items-center nx:gap-2\">\n      <Switch id=\"switch-demo-airplane\" />\n      <Label htmlFor=\"switch-demo-airplane\">Airplane mode</Label>\n    </div>\n  );\n}\n";
