// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./disabled.client";

export const source = "'use client';\n\nimport { Switch } from '@/components/switch/switch';\n\nexport default function SwitchDisabled() {\n  return (\n    <div className=\"nx:flex nx:flex-col nx:gap-3\">\n      <div className=\"nx:flex nx:items-center nx:gap-2\">\n        <Switch id=\"switch-disabled-off\" disabled />\n        <label\n          htmlFor=\"switch-disabled-off\"\n          className=\"nx:typography-label-default nx:peer-disabled:cursor-not-allowed nx:peer-disabled:text-disabled-foreground\"\n        >\n          Off\n        </label>\n      </div>\n      <div className=\"nx:flex nx:items-center nx:gap-2\">\n        <Switch id=\"switch-disabled-on\" disabled defaultChecked />\n        <label\n          htmlFor=\"switch-disabled-on\"\n          className=\"nx:typography-label-default nx:peer-disabled:cursor-not-allowed nx:peer-disabled:text-disabled-foreground\"\n        >\n          On\n        </label>\n      </div>\n    </div>\n  );\n}\n";
