// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./disabled.client";

export const source = "'use client';\n\nimport { Label } from '@/components/label/label';\nimport { Switch } from '@/components/switch/switch';\n\nexport default function SwitchDisabled() {\n  return (\n    <div className=\"nx:flex nx:flex-col nx:gap-3\">\n      <div className=\"nx:flex nx:items-center nx:gap-2\">\n        <Switch id=\"switch-disabled-location\" disabled />\n        <Label htmlFor=\"switch-disabled-location\">Location services</Label>\n      </div>\n      <div className=\"nx:flex nx:items-center nx:gap-2\">\n        <Switch id=\"switch-disabled-updates\" disabled defaultChecked />\n        <Label htmlFor=\"switch-disabled-updates\">Automatic updates</Label>\n      </div>\n    </div>\n  );\n}\n";
