// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./sizes.client";

export const source = "'use client';\n\nimport { Switch } from '@/components/switch/switch';\n\nexport default function SwitchSizes() {\n  return (\n    <div className=\"nx:flex nx:flex-col nx:gap-3\">\n      <div className=\"nx:flex nx:items-center nx:gap-2\">\n        <Switch id=\"switch-sizes-sm\" size=\"sm\" />\n        <label\n          htmlFor=\"switch-sizes-sm\"\n          className=\"nx:typography-label-default\"\n        >\n          Small\n        </label>\n      </div>\n      <div className=\"nx:flex nx:items-center nx:gap-2\">\n        <Switch id=\"switch-sizes-default\" size=\"default\" />\n        <label\n          htmlFor=\"switch-sizes-default\"\n          className=\"nx:typography-label-default\"\n        >\n          Default\n        </label>\n      </div>\n    </div>\n  );\n}\n";
