// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./sizes.client";

export const source = "'use client';\n\nimport { Label } from '@/components/label/label';\nimport { Switch } from '@/components/switch/switch';\n\nexport default function SwitchSizes() {\n  return (\n    <div className=\"nx:flex nx:flex-col nx:gap-3\">\n      <div className=\"nx:flex nx:items-center nx:gap-2\">\n        <Switch id=\"switch-sizes-sm\" size=\"sm\" />\n        <Label htmlFor=\"switch-sizes-sm\">Small</Label>\n      </div>\n      <div className=\"nx:flex nx:items-center nx:gap-2\">\n        <Switch id=\"switch-sizes-default\" size=\"default\" />\n        <Label htmlFor=\"switch-sizes-default\">Default</Label>\n      </div>\n    </div>\n  );\n}\n";
