// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./with-description.client";

export const source = "'use client';\n\nimport { Switch } from '@/components/switch/switch';\n\nexport default function SwitchWithDescription() {\n  return (\n    <div className=\"nx:flex nx:items-center nx:justify-between nx:gap-4 nx:rounded-lg nx:border-default nx:border-border-default nx:p-4\">\n      <div className=\"nx:space-y-0.5\">\n        <label\n          htmlFor=\"switch-with-description-marketing\"\n          className=\"nx:typography-label-default\"\n        >\n          Marketing emails\n        </label>\n        <p className=\"nx:typography-body-default nx:text-muted-foreground\">\n          Receive emails about new products and features.\n        </p>\n      </div>\n      <Switch id=\"switch-with-description-marketing\" />\n    </div>\n  );\n}\n";
