// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./checked.client";

export const source = "'use client';\n\nimport { Checkbox } from '@/components/checkbox/checkbox';\nimport { Label } from '@/components/label/label';\n\nexport default function CheckboxChecked() {\n  return (\n    <div className=\"nx:flex nx:flex-col nx:gap-3\">\n      <div className=\"nx:flex nx:items-center nx:gap-2\">\n        <Checkbox id=\"checkbox-checked-off\" />\n        <Label htmlFor=\"checkbox-checked-off\">Unchecked</Label>\n      </div>\n      <div className=\"nx:flex nx:items-center nx:gap-2\">\n        <Checkbox id=\"checkbox-checked-on\" defaultChecked />\n        <Label htmlFor=\"checkbox-checked-on\">Checked</Label>\n      </div>\n    </div>\n  );\n}\n";
