// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./checked.client";

export const source = "'use client';\n\nimport { Checkbox } from '@/components/checkbox/checkbox';\n\nexport default function CheckboxChecked() {\n  return (\n    <div className=\"nx:flex nx:flex-col nx:gap-3\">\n      <div className=\"nx:flex nx:items-center nx:gap-2\">\n        <Checkbox id=\"checkbox-checked-off\" />\n        <label\n          htmlFor=\"checkbox-checked-off\"\n          className=\"nx:typography-label-default nx:text-foreground nx:select-none\"\n        >\n          Unchecked\n        </label>\n      </div>\n      <div className=\"nx:flex nx:items-center nx:gap-2\">\n        <Checkbox id=\"checkbox-checked-on\" defaultChecked />\n        <label\n          htmlFor=\"checkbox-checked-on\"\n          className=\"nx:typography-label-default nx:text-foreground nx:select-none\"\n        >\n          Checked\n        </label>\n      </div>\n    </div>\n  );\n}\n";
