// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./demo.client";

export const source = "'use client';\n\nimport {\n  Tabs,\n  TabsContent,\n  TabsList,\n  TabsTrigger,\n} from '@/components/tabs/tabs';\n\nexport default function TabsDemo() {\n  return (\n    <Tabs defaultValue=\"account\" className=\"nx:w-full nx:max-w-sm\">\n      <TabsList>\n        <TabsTrigger value=\"account\">Account</TabsTrigger>\n        <TabsTrigger value=\"password\">Password</TabsTrigger>\n      </TabsList>\n      <TabsContent value=\"account\">\n        <p className=\"nx:typography-body-default nx:text-muted-foreground\">\n          Update your name and email address.\n        </p>\n      </TabsContent>\n      <TabsContent value=\"password\">\n        <p className=\"nx:typography-body-default nx:text-muted-foreground\">\n          Change the password you sign in with.\n        </p>\n      </TabsContent>\n    </Tabs>\n  );\n}\n";
