// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./demo.client";

export const source = "'use client';\n\nimport {\n  Avatar,\n  AvatarFallback,\n  AvatarImage,\n} from '@/components/avatar/avatar';\n\nexport default function AvatarDemo() {\n  return (\n    <Avatar>\n      <AvatarImage src=\"/avatars/ada.svg\" alt=\"Ada Lovelace\" />\n      <AvatarFallback>AL</AvatarFallback>\n    </Avatar>\n  );\n}\n";
