// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./group.client";

export const source = "'use client';\n\nimport {\n  Avatar,\n  AvatarFallback,\n  AvatarGroup,\n  AvatarImage,\n} from '@/components/avatar/avatar';\n\nconst team = [\n  { name: 'Ada Lovelace', initials: 'AL', src: '/avatars/ada.svg' },\n  { name: 'Grace Hopper', initials: 'GH', src: '/avatars/grace.svg' },\n  { name: 'Katherine Johnson', initials: 'KJ', src: '/avatars/katherine.svg' },\n  { name: 'Mary Jackson', initials: 'MJ', src: '/avatars/mary.svg' },\n  { name: 'Dorothy Vaughan', initials: 'DV', src: '/avatars/dorothy.svg' },\n];\n\nexport default function AvatarGroupDemo() {\n  return (\n    <AvatarGroup max={3} role=\"group\" aria-label=\"Project team\">\n      {team.map((person) => (\n        <Avatar key={person.name}>\n          <AvatarImage src={person.src} alt={person.name} />\n          <AvatarFallback>{person.initials}</AvatarFallback>\n        </Avatar>\n      ))}\n    </AvatarGroup>\n  );\n}\n";
