// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./shapes.client";

export const source = "'use client';\n\nimport {\n  Avatar,\n  AvatarFallback,\n  AvatarImage,\n} from '@/components/avatar/avatar';\n\nexport default function AvatarShapes() {\n  return (\n    <div className=\"nx:flex nx:items-center nx:gap-4\">\n      <Avatar size=\"lg\" shape=\"circle\">\n        <AvatarImage src=\"/avatars/grace.svg\" alt=\"Grace Hopper\" />\n        <AvatarFallback>GH</AvatarFallback>\n      </Avatar>\n      <Avatar size=\"lg\" shape=\"rounded\">\n        <AvatarImage src=\"/avatars/grace.svg\" alt=\"Grace Hopper\" />\n        <AvatarFallback>GH</AvatarFallback>\n      </Avatar>\n    </div>\n  );\n}\n";
