// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./demo.client";

export const source = "'use client';\n\nimport { AspectRatio } from '@/components/aspect-ratio/aspect-ratio';\n\nexport default function AspectRatioDemo() {\n  return (\n    <div className=\"nx:w-full nx:max-w-sm\">\n      <AspectRatio ratio={16 / 9}>\n        <div className=\"nx:flex nx:size-full nx:items-center nx:justify-center nx:rounded-md nx:bg-muted nx:text-muted-foreground nx:typography-label-small\">\n          16 / 9\n        </div>\n      </AspectRatio>\n    </div>\n  );\n}\n";
