// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./ratios.client";

export const source = "'use client';\n\nimport { AspectRatio } from '@/components/aspect-ratio/aspect-ratio';\n\nexport default function AspectRatioRatios() {\n  return (\n    <div className=\"nx:flex nx:flex-wrap nx:items-start nx:gap-4\">\n      <div className=\"nx:w-40\">\n        <AspectRatio ratio={1}>\n          <div className=\"nx:flex nx:size-full nx:items-center nx:justify-center nx:rounded-md nx:bg-muted nx:text-muted-foreground nx:typography-label-small\">\n            1 / 1\n          </div>\n        </AspectRatio>\n      </div>\n      <div className=\"nx:w-40\">\n        <AspectRatio ratio={4 / 3}>\n          <div className=\"nx:flex nx:size-full nx:items-center nx:justify-center nx:rounded-md nx:bg-muted nx:text-muted-foreground nx:typography-label-small\">\n            4 / 3\n          </div>\n        </AspectRatio>\n      </div>\n    </div>\n  );\n}\n";
