// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./fills.client";

export const source = "'use client';\n\nimport { Badge, type BadgeProps } from '@/components/badge/badge';\n\nconst variants = [\n  'default',\n  'secondary',\n  'success',\n  'warning',\n  'error',\n  'information',\n] as const satisfies NonNullable<BadgeProps['variant']>[];\n\nconst fills = ['solid', 'light', 'outline'] as const satisfies NonNullable<\n  BadgeProps['fill']\n>[];\n\nexport default function BadgeFills() {\n  return (\n    <div className=\"nx:flex nx:flex-col nx:gap-3\">\n      {fills.map((fill) => (\n        <div\n          key={fill}\n          className=\"nx:flex nx:flex-wrap nx:items-center nx:gap-2\"\n        >\n          {variants.map((variant) => (\n            <Badge key={variant} variant={variant} fill={fill}>\n              {variant}\n            </Badge>\n          ))}\n        </div>\n      ))}\n    </div>\n  );\n}\n";
