// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./icon-only.client";

export const source = "'use client';\n\nimport {\n  IconAlertTriangle,\n  IconCircleCheck,\n  IconCircleX,\n} from '@tabler/icons-react';\n\nimport { Badge } from '@/components/badge/badge';\n\nexport default function BadgeIconOnly() {\n  return (\n    <div className=\"nx:flex nx:flex-wrap nx:items-center nx:gap-2\">\n      <Badge\n        variant=\"success\"\n        leftIcon={<IconCircleCheck />}\n        aria-label=\"Verified\"\n        title=\"Verified\"\n      />\n      <Badge\n        variant=\"warning\"\n        leftIcon={<IconAlertTriangle />}\n        aria-label=\"Pending review\"\n        title=\"Pending review\"\n      />\n      <Badge\n        variant=\"error\"\n        leftIcon={<IconCircleX />}\n        aria-label=\"Failed\"\n        title=\"Failed\"\n      />\n    </div>\n  );\n}\n";
