// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./variants.client";

export const source = "import { Badge } from '@nexus_ds/react';\n\nexport default function BadgeVariants() {\n  return (\n    <div className=\"nx:flex nx:flex-wrap nx:items-center nx:gap-2\">\n      <Badge variant=\"default\">Default</Badge>\n      <Badge variant=\"secondary\">Secondary</Badge>\n      <Badge variant=\"success\">Success</Badge>\n      <Badge variant=\"warning\">Warning</Badge>\n      <Badge variant=\"error\">Error</Badge>\n      <Badge variant=\"information\">Information</Badge>\n    </div>\n  );\n}\n";
