// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./with-icon.client";

export const source = "'use client';\n\nimport {\n  IconAlertTriangle,\n  IconArrowUpRight,\n  IconCircleCheck,\n} from '@tabler/icons-react';\n\nimport { Badge } from '@/components/badge/badge';\n\nexport default function BadgeWithIcon() {\n  return (\n    <div className=\"nx:flex nx:flex-wrap nx:items-center nx:gap-2\">\n      <Badge variant=\"success\" fill=\"light\" leftIcon={<IconCircleCheck />}>\n        Verified\n      </Badge>\n      <Badge variant=\"warning\" fill=\"light\" leftIcon={<IconAlertTriangle />}>\n        Pending\n      </Badge>\n      <Badge variant=\"information\" rightIcon={<IconArrowUpRight />}>\n        Trending\n      </Badge>\n    </div>\n  );\n}\n";
