// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./demo.client";

export const source = "'use client';\n\nimport { Input } from '@/components/input/input';\n\nexport default function InputDemo() {\n  return (\n    <Input\n      className=\"nx:max-w-sm\"\n      type=\"email\"\n      placeholder=\"you@example.com\"\n      aria-label=\"Email\"\n    />\n  );\n}\n";
