// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./disabled.client";

export const source = "'use client';\n\nimport { Input } from '@/components/input/input';\n\nexport default function InputDisabled() {\n  return (\n    <div className=\"nx:flex nx:w-full nx:max-w-sm nx:flex-col nx:gap-3\">\n      <Input disabled placeholder=\"Disabled\" aria-label=\"Disabled\" />\n      <Input\n        disabled\n        defaultValue=\"acct_1024\"\n        aria-label=\"Disabled with value\"\n      />\n    </div>\n  );\n}\n";
