// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./invalid.client";

export const source = "'use client';\n\nimport { Field, FieldError, FieldLabel } from '@/components/field/field';\nimport { Input } from '@/components/input/input';\n\nexport default function InputInvalid() {\n  return (\n    <Field data-invalid=\"true\" className=\"nx:max-w-sm\">\n      <FieldLabel htmlFor=\"input-invalid-email\">Email</FieldLabel>\n      <Input\n        id=\"input-invalid-email\"\n        type=\"email\"\n        defaultValue=\"ada@\"\n        aria-invalid\n        aria-describedby=\"input-invalid-email-error\"\n      />\n      <FieldError id=\"input-invalid-email-error\">\n        Enter a complete email address.\n      </FieldError>\n    </Field>\n  );\n}\n";
