// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./invalid.client";

export const source = "'use client';\n\nimport { Input } from '@/components/input/input';\n\nexport default function InputInvalid() {\n  return (\n    <div className=\"nx:grid nx:w-full nx:max-w-sm nx:gap-1.5\">\n      <label\n        htmlFor=\"input-invalid-email\"\n        className=\"nx:typography-label-default nx:text-foreground\"\n      >\n        Email\n      </label>\n      <Input\n        id=\"input-invalid-email\"\n        type=\"email\"\n        defaultValue=\"ada@\"\n        aria-invalid\n        aria-describedby=\"input-invalid-email-error\"\n      />\n      <p\n        id=\"input-invalid-email-error\"\n        className=\"nx:typography-body-small nx:text-error-subtle-foreground\"\n      >\n        Enter a complete email address.\n      </p>\n    </div>\n  );\n}\n";
