// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./sizes.client";

export const source = "'use client';\n\nimport { Input } from '@/components/input/input';\n\nexport default function InputSizes() {\n  return (\n    <div className=\"nx:flex nx:w-full nx:max-w-sm nx:flex-col nx:gap-3\">\n      <Input size=\"sm\" placeholder=\"Small\" aria-label=\"Small\" />\n      <Input size=\"default\" placeholder=\"Default\" aria-label=\"Default\" />\n      <Input size=\"lg\" placeholder=\"Large\" aria-label=\"Large\" />\n    </div>\n  );\n}\n";
