// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./variants.client";

export const source = "'use client';\n\nimport { Input } from '@/components/input/input';\n\nexport default function InputVariants() {\n  return (\n    <div className=\"nx:flex nx:w-full nx:max-w-sm nx:flex-col nx:gap-3\">\n      <Input variant=\"bordered\" placeholder=\"Bordered\" aria-label=\"Bordered\" />\n      <Input\n        variant=\"borderless\"\n        placeholder=\"Borderless\"\n        aria-label=\"Borderless\"\n      />\n    </div>\n  );\n}\n";
