// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./with-label.client";

export const source = "'use client';\n\nimport { Input } from '@/components/input/input';\nimport { Label } from '@/components/label/label';\n\nexport default function InputWithLabel() {\n  return (\n    <div className=\"nx:grid nx:w-full nx:max-w-sm nx:gap-1.5\">\n      <Label htmlFor=\"input-with-label-name\">Full name</Label>\n      <Input id=\"input-with-label-name\" placeholder=\"Ada Lovelace\" />\n    </div>\n  );\n}\n";
