// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

import type { ComponentType } from 'react';

export interface Demo {
  /** Path under apps/docs/examples/ without the .tsx extension. */
  id: string;
  /** Loads the demo's component and its own source text together. */
  load: () => Promise<{ Component: ComponentType; source: string }>;
}

export const demos = {
  "badge/demo": {
    id: "badge/demo",
    load: () => import("./demos/badge/demo"),
  },
  "badge/variants": {
    id: "badge/variants",
    load: () => import("./demos/badge/variants"),
  },
  "button/demo": {
    id: "button/demo",
    load: () => import("./demos/button/demo"),
  },
  "button/disabled": {
    id: "button/disabled",
    load: () => import("./demos/button/disabled"),
  },
  "button/sizes": {
    id: "button/sizes",
    load: () => import("./demos/button/sizes"),
  },
  "button/variants": {
    id: "button/variants",
    load: () => import("./demos/button/variants"),
  },
  "button/with-icon": {
    id: "button/with-icon",
    load: () => import("./demos/button/with-icon"),
  },
  "getting-started/button-core-variants": {
    id: "getting-started/button-core-variants",
    load: () => import("./demos/getting-started/button-core-variants"),
  },
  "input/demo": {
    id: "input/demo",
    load: () => import("./demos/input/demo"),
  },
  "input/disabled": {
    id: "input/disabled",
    load: () => import("./demos/input/disabled"),
  },
  "input/invalid": {
    id: "input/invalid",
    load: () => import("./demos/input/invalid"),
  },
  "input/sizes": {
    id: "input/sizes",
    load: () => import("./demos/input/sizes"),
  },
  "input/variants": {
    id: "input/variants",
    load: () => import("./demos/input/variants"),
  },
  "input/with-label": {
    id: "input/with-label",
    load: () => import("./demos/input/with-label"),
  },
} satisfies Record<string, Demo>;

export type DemoId = keyof typeof demos;

export function isDemoId(id: string): id is DemoId {
  return Object.hasOwn(demos, id);
}

export function getDemo(id: string): Demo {
  if (!isDemoId(id)) {
    throw new Error(
      `Unknown demo id: ${id}. Add apps/docs/examples/${id}.tsx, or fix the id.`
    );
  }

  return demos[id];
}
