// AUTO-GENERATED by apps/docs/scripts/generate-page-manifest.mjs — do not edit.
// Regenerate with `pnpm --filter @nexus_ds/docs generate:manifest`.

import type { ComponentType } from 'react';

import type { Block } from '../../page-registry/blocks';

// The thunks below import page and MDX modules, so a `'use client'` importer
// would pull the whole docs body into the client bundle.
import 'server-only';

// eslint-disable-next-line @nexus_ds/no-render-prop-types -- `default: ComponentType` is the shape of a lazily-imported page module, not a component-as-prop.
export type ManifestPageLoader = () => Promise<{ default: ComponentType }>;

export type PageWireframe = {
  lede: string;
  blocks: readonly Block[];
};

/** Route → page module, for every `PAGE_MANIFEST` entry with a source file. */
export const PAGE_LOADERS: Record<string, ManifestPageLoader> = {
  '/getting-started/install': () =>
    import('../../content/getting-started/install.mdx'),
  '/getting-started/theme-setup': () =>
    import('../../content/getting-started/theme-setup.mdx'),
  '/foundations/color': () => import('../_pages/foundations/color'),
  '/foundations/typography': () => import('../_pages/foundations/typography'),
  '/foundations/spacing': () => import('../_pages/foundations/spacing'),
  '/foundations/radius': () => import('../_pages/foundations/radius'),
  '/foundations/focus': () => import('../_pages/foundations/focus'),
  '/foundations/layering': () => import('../_pages/foundations/layering'),
  '/foundations/responsive': () => import('../_pages/foundations/responsive'),
  '/components/accordion': () =>
    import('../../content/components/accordion.mdx'),
  '/components/alert': () => import('../../content/components/alert.mdx'),
  '/components/alert-dialog': () =>
    import('../../content/components/alert-dialog.mdx'),
  '/components/aspect-ratio': () =>
    import('../../content/components/aspect-ratio.mdx'),
  '/components/attachment': () =>
    import('../../content/components/attachment.mdx'),
  '/components/avatar': () => import('../../content/components/avatar.mdx'),
  '/components/badge': () => import('../../content/components/badge.mdx'),
  '/components/breadcrumb': () =>
    import('../../content/components/breadcrumb.mdx'),
  '/components/bubble': () => import('../../content/components/bubble.mdx'),
  '/components/button': () => import('../../content/components/button.mdx'),
  '/components/button-group': () =>
    import('../../content/components/button-group.mdx'),
  '/components/carousel': () => import('../../content/components/carousel.mdx'),
  '/components/chart': () => import('../../content/components/chart.mdx'),
  '/theming/appearance': () => import('../../content/theming/appearance.mdx'),
  '/theming/multi-brand': () => import('../_pages/theming/multi-brand'),
  '/theming/radius-overrides': () =>
    import('../../content/theming/radius-overrides.mdx'),
};

/** Route → registry wireframe, for every `kind: 'placeholder'` entry. */
export const PAGE_WIREFRAMES: Record<string, PageWireframe> = {
  '/getting-started/first-component': {
    lede: '[ Render a Button, swap a variant, observe the data attributes ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code block — JSX import + render ]',
      },
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Storybook embed — Button playground ]',
      },
    ],
  },
  '/getting-started/designers': {
    lede: '[ Open the Figma library · use the variables · sync via Code Connect ]',
    blocks: [
      {
        type: 'placeholder',
        label: '[ External-link list — Figma library, Code Connect docs ]',
      },
      {
        type: 'placeholder',
        variant: 'diagram',
        label: '[ Diagram — code ↔ Figma parity flow ]',
      },
    ],
  },
  '/getting-started/agents': {
    lede: '[ Point your agent at llms.txt · load the rule files · use the system prompt ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code block — system-prompt snippet ]',
      },
      {
        type: 'placeholder',
        label: '[ Download / copy buttons — llms.txt, rules.zip ]',
      },
    ],
  },
  '/components/appearance': {
    lede: '[ Appearance — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/card': {
    lede: '[ Card — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/checkbox': {
    lede: '[ Checkbox — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/choice-card': {
    lede: '[ ChoiceCard — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/choice-row': {
    lede: '[ ChoiceRow — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/collapsible': {
    lede: '[ Collapsible — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/combobox': {
    lede: '[ Combobox — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/command': {
    lede: '[ Command — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/context-menu': {
    lede: '[ ContextMenu — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/date-picker': {
    lede: '[ DatePicker — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/dialog': {
    lede: '[ Dialog — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/drawer': {
    lede: '[ Drawer — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/dropdown-menu': {
    lede: '[ DropdownMenu — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/empty-state': {
    lede: '[ EmptyState — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/field': {
    lede: '[ Field — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/hide': {
    lede: '[ Hide — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/hover-card': {
    lede: '[ HoverCard — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/input': {
    lede: '[ Input — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/input-group': {
    lede: '[ InputGroup — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/input-otp': {
    lede: '[ InputOTP — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/item': {
    lede: '[ Item — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/kbd': {
    lede: '[ Kbd — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/label': {
    lede: '[ Label — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/marker': {
    lede: '[ Marker — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/menubar': {
    lede: '[ Menubar — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/multi-select': {
    lede: '[ MultiSelect — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/native-select': {
    lede: '[ NativeSelect — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/navigation-menu': {
    lede: '[ NavigationMenu — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/pagination': {
    lede: '[ Pagination — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/popover': {
    lede: '[ Popover — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/progress': {
    lede: '[ Progress — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/radio-group': {
    lede: '[ RadioGroup — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/resizable': {
    lede: '[ Resizable — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/scroll-area': {
    lede: '[ ScrollArea — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/select': {
    lede: '[ Select — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/separator': {
    lede: '[ Separator — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/sheet': {
    lede: '[ Sheet — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/show': {
    lede: '[ Show — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/sidebar': {
    lede: '[ Sidebar — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/skeleton': {
    lede: '[ Skeleton — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/slider': {
    lede: '[ Slider — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/sonner': {
    lede: '[ Sonner — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/spinner': {
    lede: '[ Spinner — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/switch': {
    lede: '[ Switch — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/table': {
    lede: '[ Table — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/tabs': {
    lede: '[ Tabs — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/textarea': {
    lede: '[ Textarea — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/toggle': {
    lede: '[ Toggle — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/toggle-group': {
    lede: '[ ToggleGroup — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/components/tooltip': {
    lede: '[ Tooltip — page coming soon ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Preview · Installation · Code · Props · Examples ]',
      },
    ],
  },
  '/theming/density-modes': {
    lede: '[ Spacing density via data-density ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'tall',
        label:
          '[ Live demo — 6-mode grid · same component, different density ]',
      },
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — data-density attribute pattern ]',
      },
    ],
  },
  '/theming/overrides': {
    lede: '[ Re-point a token via CSS variable in your stylesheet ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — :root override pattern ]',
      },
      {
        type: 'placeholder',
        label: "[ Body — what's safe to override, what isn't ]",
      },
    ],
  },
  '/tools/nx-prefix': {
    lede: '[ Why everything is prefixed · how it composes with modifiers ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'code',
        label: "[ Code — examples · do / don't ]",
      },
      {
        type: 'placeholder',
        variant: 'table',
        label: '[ Table — prefix placement rules ]',
      },
    ],
  },
  '/tools/code-connect': {
    lede: '[ Mapping Figma components to code · maintaining .figma.ts ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — example .figma.ts ]',
      },
      {
        type: 'placeholder',
        variant: 'diagram',
        label: '[ Diagram — Figma ↔ code parity ]',
      },
    ],
  },
  '/tools/eslint': {
    lede: '[ @nexus_ds/eslint-plugin · canonical-spacing-steps · class conventions ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — install + config ]',
      },
      {
        type: 'placeholder',
        variant: 'table',
        label: '[ Table — rules · severity · what they flag ]',
      },
    ],
  },
  '/tools/audits': {
    lede: '[ figma-parity · APCA contrast · spacing-modes ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'table',
        label: '[ Table — audit · command · exit codes · what it catches ]',
      },
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — CI workflow snippet ]',
      },
    ],
  },
  '/tools/storybook': {
    lede: '[ Stories-as-tests · autodocs · base-variant grids ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Storybook embed — example component ]',
      },
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — story template ]',
      },
    ],
  },
  '/guidance/engineering': {
    lede: '[ Simplicity over cleverness · guard clauses · composition · ripple effect ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'table',
        label: '[ Table — principle · rule file · one-line summary ]',
      },
      {
        type: 'placeholder',
        label: '[ Cards — each rule from code-quality.md children ]',
      },
    ],
  },
  '/guidance/testing': {
    lede: '[ Stories are tests · vitest projects · APCA at the token layer ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'diagram',
        label: '[ Diagram — what runs where (storybook / unit / audits) ]',
      },
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — play function example ]',
      },
    ],
  },
  '/guidance/contribution': {
    lede: '[ Branch · PR title · review accounts · DoD ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'diagram',
        label: '[ Diagram — issue → branch → PR → review → merge ]',
      },
      {
        type: 'placeholder',
        variant: 'table',
        label: '[ Table — verdicts · review events · who posts ]',
      },
    ],
  },
  '/agents/llms-txt': {
    lede: '[ Point your model at one URL · machine-readable site map ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — llms.txt preview ]',
      },
      { type: 'placeholder', label: '[ Download · copy link ]' },
    ],
  },
  '/agents/rules-mirror': {
    lede: '[ All 17 rule files · readable on the web · always up to date ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'table',
        label: '[ Table — rule file · purpose · related ]',
      },
    ],
  },
  '/agents/authoring': {
    lede: '[ Copy-paste system prompts · authoring conventions · common pitfalls ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — system prompt template ]',
      },
      { type: 'placeholder', label: "[ Do / Don't list ]" },
    ],
  },
};
