// AUTO-GENERATED by apps/docs/scripts/generate-page-manifest.mjs — do not edit.
// Regenerate with `pnpm --filter @nexus_ds/docs generate:manifest`.

type ManifestPageBase = {
  /** Route path, e.g. `/foundations/color`. */
  route: string;
  slug: string;
  label: string;
};

type PlaceholderPage = {
  /** No page file yet; the body is `PAGE_WIREFRAMES[route]`. */
  kind: 'placeholder';
  file: null;
};

export type GuideManifestPage = ManifestPageBase & {
  /** Non-interactive headings listed under this page in the left rail. */
  nested?: readonly string[];
} & (
    | {
        kind: 'mdx' | 'component';
        /** Source file relative to `apps/docs`; the module is `PAGE_LOADERS[route]`. */
        file: string;
      }
    | PlaceholderPage
  );

/**
 * A component `@nexus_ds/react` exports. Once `components/{slug}.mdx` is
 * written it renders `<ComponentPage slug="{slug}" />`; until then, a placeholder.
 */
export type ComponentManifestPage = ManifestPageBase & {
  nested?: never;
} & (
    | {
        kind: 'mdx';
        /** Source file relative to `apps/docs`; the module is `PAGE_LOADERS[route]`. */
        file: string;
        /** Example demo names the page shows first, in this order. */
        examples: readonly string[];
      }
    | PlaceholderPage
  );

export type ManifestPage = GuideManifestPage | ComponentManifestPage;

type ManifestSectionBase = {
  slug: string;
  title: string;
  href: string;
};

export type GuideManifestSection = ManifestSectionBase & {
  unit?: never;
  pages: readonly GuideManifestPage[];
};

export type ComponentsManifestSection = ManifestSectionBase & {
  /** What the section is counted in on the home page. Other sections count pages. */
  unit: 'components';
  pages: readonly ComponentManifestPage[];
};

export type ManifestSection = GuideManifestSection | ComponentsManifestSection;

/** The separator the home page's section cards join a section's page labels with. */
export const CARD_JOINER = ' · ';

/** Every docs page, in nav order. Serializable — safe to import from a client component. */
export const PAGE_MANIFEST: readonly ManifestSection[] = [
  {
    slug: 'getting-started',
    title: 'Getting Started',
    href: '/getting-started',
    pages: [
      {
        route: '/getting-started/install',
        slug: 'install',
        label: 'Install',
        kind: 'mdx',
        file: 'content/getting-started/install.mdx',
      },
      {
        route: '/getting-started/theme-setup',
        slug: 'theme-setup',
        label: 'Theme setup',
        kind: 'mdx',
        file: 'content/getting-started/theme-setup.mdx',
      },
      {
        route: '/getting-started/first-component',
        slug: 'first-component',
        label: 'Your first component',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/getting-started/designers',
        slug: 'designers',
        label: 'For designers',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/getting-started/agents',
        slug: 'agents',
        label: 'For AI agents',
        kind: 'placeholder',
        file: null,
      },
    ],
  },
  {
    slug: 'foundations',
    title: 'Foundations',
    href: '/foundations',
    pages: [
      {
        route: '/foundations/color',
        slug: 'color',
        label: 'Color',
        nested: [
          'How color works',
          'Palette & shades',
          'Surfaces',
          'Accessibility',
        ],
        kind: 'component',
        file: 'app/_pages/foundations/color.tsx',
      },
      {
        route: '/foundations/typography',
        slug: 'typography',
        label: 'Typography',
        kind: 'component',
        file: 'app/_pages/foundations/typography.tsx',
      },
      {
        route: '/foundations/spacing',
        slug: 'spacing',
        label: 'Spacing',
        kind: 'component',
        file: 'app/_pages/foundations/spacing.tsx',
      },
      {
        route: '/foundations/radius',
        slug: 'radius',
        label: 'Radius, borders & shadows',
        kind: 'component',
        file: 'app/_pages/foundations/radius.tsx',
      },
      {
        route: '/foundations/focus',
        slug: 'focus',
        label: 'Focus',
        kind: 'component',
        file: 'app/_pages/foundations/focus.tsx',
      },
      {
        route: '/foundations/layering',
        slug: 'layering',
        label: 'Layering',
        kind: 'component',
        file: 'app/_pages/foundations/layering.tsx',
      },
      {
        route: '/foundations/responsive',
        slug: 'responsive',
        label: 'Responsive',
        kind: 'component',
        file: 'app/_pages/foundations/responsive.tsx',
      },
    ],
  },
  {
    slug: 'components',
    title: 'Components',
    href: '/components',
    unit: 'components',
    pages: [
      {
        route: '/components/accordion',
        slug: 'accordion',
        label: 'Accordion',
        examples: ['floating', 'multiple', 'disabled'],
        kind: 'mdx',
        file: 'content/components/accordion.mdx',
      },
      {
        route: '/components/alert',
        slug: 'alert',
        label: 'Alert',
        examples: ['variants', 'with-actions', 'dismissible', 'banner'],
        kind: 'mdx',
        file: 'content/components/alert.mdx',
      },
      {
        route: '/components/alert-dialog',
        slug: 'alert-dialog',
        label: 'AlertDialog',
        examples: ['destructive-action', 'center'],
        kind: 'mdx',
        file: 'content/components/alert-dialog.mdx',
      },
      {
        route: '/components/appearance',
        slug: 'appearance',
        label: 'Appearance',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/aspect-ratio',
        slug: 'aspect-ratio',
        label: 'AspectRatio',
        examples: ['ratios'],
        kind: 'mdx',
        file: 'content/components/aspect-ratio.mdx',
      },
      {
        route: '/components/attachment',
        slug: 'attachment',
        label: 'Attachment',
        examples: ['states', 'sizes', 'group'],
        kind: 'mdx',
        file: 'content/components/attachment.mdx',
      },
      {
        route: '/components/avatar',
        slug: 'avatar',
        label: 'Avatar',
        examples: ['sizes', 'shapes', 'with-status', 'group'],
        kind: 'mdx',
        file: 'content/components/avatar.mdx',
      },
      {
        route: '/components/badge',
        slug: 'badge',
        label: 'Badge',
        examples: ['variants', 'fills', 'with-icon', 'icon-only'],
        kind: 'mdx',
        file: 'content/components/badge.mdx',
      },
      {
        route: '/components/breadcrumb',
        slug: 'breadcrumb',
        label: 'Breadcrumb',
        examples: ['with-ellipsis', 'with-icons', 'with-menu'],
        kind: 'mdx',
        file: 'content/components/breadcrumb.mdx',
      },
      {
        route: '/components/bubble',
        slug: 'bubble',
        label: 'Bubble',
        examples: ['variants', 'with-reactions'],
        kind: 'mdx',
        file: 'content/components/bubble.mdx',
      },
      {
        route: '/components/button',
        slug: 'button',
        label: 'Button',
        examples: ['variants', 'sizes', 'with-icon', 'disabled'],
        kind: 'mdx',
        file: 'content/components/button.mdx',
      },
      {
        route: '/components/button-group',
        slug: 'button-group',
        label: 'ButtonGroup',
        examples: ['sizes', 'vertical', 'with-text', 'with-separator'],
        kind: 'mdx',
        file: 'content/components/button-group.mdx',
      },
      {
        route: '/components/card',
        slug: 'card',
        label: 'Card',
        examples: [
          'header-with-action',
          'content-only',
          'footer-actions',
          'sign-in-form',
        ],
        kind: 'mdx',
        file: 'content/components/card.mdx',
      },
      {
        route: '/components/carousel',
        slug: 'carousel',
        label: 'Carousel',
        examples: ['vertical'],
        kind: 'mdx',
        file: 'content/components/carousel.mdx',
      },
      {
        route: '/components/chart',
        slug: 'chart',
        label: 'Chart',
        examples: ['area', 'line'],
        kind: 'mdx',
        file: 'content/components/chart.mdx',
      },
      {
        route: '/components/checkbox',
        slug: 'checkbox',
        label: 'Checkbox',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/choice-card',
        slug: 'choice-card',
        label: 'ChoiceCard',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/choice-row',
        slug: 'choice-row',
        label: 'ChoiceRow',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/collapsible',
        slug: 'collapsible',
        label: 'Collapsible',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/combobox',
        slug: 'combobox',
        label: 'Combobox',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/command',
        slug: 'command',
        label: 'Command',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/context-menu',
        slug: 'context-menu',
        label: 'ContextMenu',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/date-picker',
        slug: 'date-picker',
        label: 'DatePicker',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/dialog',
        slug: 'dialog',
        label: 'Dialog',
        examples: ['with-form', 'prop-driven', 'scrollable-body'],
        kind: 'mdx',
        file: 'content/components/dialog.mdx',
      },
      {
        route: '/components/drawer',
        slug: 'drawer',
        label: 'Drawer',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/dropdown-menu',
        slug: 'dropdown-menu',
        label: 'DropdownMenu',
        examples: ['checkbox-items', 'radio-items', 'submenu'],
        kind: 'mdx',
        file: 'content/components/dropdown-menu.mdx',
      },
      {
        route: '/components/empty-state',
        slug: 'empty-state',
        label: 'EmptyState',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/field',
        slug: 'field',
        label: 'Field',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/hide',
        slug: 'hide',
        label: 'Hide',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/hover-card',
        slug: 'hover-card',
        label: 'HoverCard',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/input',
        slug: 'input',
        label: 'Input',
        examples: ['variants', 'sizes', 'with-label', 'invalid', 'disabled'],
        kind: 'mdx',
        file: 'content/components/input.mdx',
      },
      {
        route: '/components/input-group',
        slug: 'input-group',
        label: 'InputGroup',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/input-otp',
        slug: 'input-otp',
        label: 'InputOTP',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/item',
        slug: 'item',
        label: 'Item',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/kbd',
        slug: 'kbd',
        label: 'Kbd',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/label',
        slug: 'label',
        label: 'Label',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/marker',
        slug: 'marker',
        label: 'Marker',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/menubar',
        slug: 'menubar',
        label: 'Menubar',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/message',
        slug: 'message',
        label: 'Message',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/message-scroller',
        slug: 'message-scroller',
        label: 'MessageScroller',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/multi-select',
        slug: 'multi-select',
        label: 'MultiSelect',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/native-select',
        slug: 'native-select',
        label: 'NativeSelect',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/navigation-menu',
        slug: 'navigation-menu',
        label: 'NavigationMenu',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/pagination',
        slug: 'pagination',
        label: 'Pagination',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/popover',
        slug: 'popover',
        label: 'Popover',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/progress',
        slug: 'progress',
        label: 'Progress',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/radio-group',
        slug: 'radio-group',
        label: 'RadioGroup',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/resizable',
        slug: 'resizable',
        label: 'Resizable',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/scroll-area',
        slug: 'scroll-area',
        label: 'ScrollArea',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/select',
        slug: 'select',
        label: 'Select',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/separator',
        slug: 'separator',
        label: 'Separator',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/sheet',
        slug: 'sheet',
        label: 'Sheet',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/show',
        slug: 'show',
        label: 'Show',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/sidebar',
        slug: 'sidebar',
        label: 'Sidebar',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/skeleton',
        slug: 'skeleton',
        label: 'Skeleton',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/slider',
        slug: 'slider',
        label: 'Slider',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/sonner',
        slug: 'sonner',
        label: 'Sonner',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/spinner',
        slug: 'spinner',
        label: 'Spinner',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/switch',
        slug: 'switch',
        label: 'Switch',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/table',
        slug: 'table',
        label: 'Table',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/tabs',
        slug: 'tabs',
        label: 'Tabs',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/textarea',
        slug: 'textarea',
        label: 'Textarea',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/toggle',
        slug: 'toggle',
        label: 'Toggle',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/toggle-group',
        slug: 'toggle-group',
        label: 'ToggleGroup',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/tooltip',
        slug: 'tooltip',
        label: 'Tooltip',
        kind: 'placeholder',
        file: null,
      },
    ],
  },
  {
    slug: 'theming',
    title: 'Theming',
    href: '/theming',
    pages: [
      {
        route: '/theming/appearance',
        slug: 'appearance',
        label: 'Appearance',
        kind: 'mdx',
        file: 'content/theming/appearance.mdx',
      },
      {
        route: '/theming/multi-brand',
        slug: 'multi-brand',
        label: 'Multi-brand',
        kind: 'component',
        file: 'app/_pages/theming/multi-brand.tsx',
      },
      {
        route: '/theming/density-modes',
        slug: 'density-modes',
        label: 'Density modes',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/theming/overrides',
        slug: 'overrides',
        label: 'Consumer overrides',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/theming/radius-overrides',
        slug: 'radius-overrides',
        label: 'Radius overrides',
        kind: 'mdx',
        file: 'content/theming/radius-overrides.mdx',
      },
    ],
  },
  {
    slug: 'tools',
    title: 'Tools',
    href: '/tools',
    pages: [
      {
        route: '/tools/nx-prefix',
        slug: 'nx-prefix',
        label: 'nx: prefix (Tailwind)',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/tools/code-connect',
        slug: 'code-connect',
        label: 'Figma Code Connect',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/tools/eslint',
        slug: 'eslint',
        label: 'ESLint plugin',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/tools/audits',
        slug: 'audits',
        label: 'Token audits',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/tools/storybook',
        slug: 'storybook',
        label: 'Storybook',
        kind: 'placeholder',
        file: null,
      },
    ],
  },
  {
    slug: 'guidance',
    title: 'Guidance',
    href: '/guidance',
    pages: [
      {
        route: '/guidance/engineering',
        slug: 'engineering',
        label: 'Engineering principles',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/guidance/testing',
        slug: 'testing',
        label: 'Testing model',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/guidance/contribution',
        slug: 'contribution',
        label: 'Contribution workflow',
        kind: 'placeholder',
        file: null,
      },
    ],
  },
  {
    slug: 'agents',
    title: 'For AI agents',
    href: '/agents',
    pages: [
      {
        route: '/agents/llms-txt',
        slug: 'llms-txt',
        label: 'llms.txt',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/agents/rules-mirror',
        slug: 'rules-mirror',
        label: 'Rules mirror',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/agents/authoring',
        slug: 'authoring',
        label: 'Agent authoring',
        kind: 'placeholder',
        file: null,
      },
    ],
  },
];
