// AUTO-GENERATED by apps/docs/scripts/generate-page-manifest.mjs — do not edit.
// Regenerate with `pnpm --filter @nexus_ds/docs generate:manifest`.

import type { ComponentType } from 'react';

import type { Block } from './blocks';

// The thunks below import page and MDX modules, so a `'use client'` importer
// would pull the whole docs body into the client bundle.
import 'server-only';

// eslint-disable-next-line @nexus_ds/no-render-prop-types -- `default: ComponentType` is the shape of a lazily-imported page module, not a component-as-prop.
export type ManifestPageLoader = () => Promise<{ default: ComponentType }>;

export type PageWireframe = {
  lede: string;
  blocks: readonly Block[];
};

/** Route → page module, for every `PAGE_MANIFEST` entry with a source file. */
export const PAGE_LOADERS: Record<string, ManifestPageLoader> = {
  '/getting-started/install': () =>
    import('../../content/getting-started/install.mdx'),
  '/getting-started/theme-setup': () =>
    import('../../content/getting-started/theme-setup.mdx'),
  '/foundations/color': () => import('../_pages/foundations/color'),
  '/foundations/typography': () => import('../_pages/foundations/typography'),
  '/foundations/spacing': () => import('../_pages/foundations/spacing'),
  '/foundations/radius': () => import('../_pages/foundations/radius'),
  '/foundations/layering': () => import('../_pages/foundations/layering'),
  '/foundations/responsive': () => import('../_pages/foundations/responsive'),
  '/theming/appearance': () => import('../../content/theming/appearance.mdx'),
  '/theming/multi-brand': () => import('../_pages/theming/multi-brand'),
};

/** Route → registry wireframe, for every `kind: 'placeholder'` entry. */
export const PAGE_WIREFRAMES: Record<string, PageWireframe> = {
  '/getting-started/first-component': {
    lede: '[ Render a Button, swap a variant, observe the data attributes ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code block — JSX import + render ]',
      },
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Storybook embed — Button playground ]',
      },
    ],
  },
  '/getting-started/designers': {
    lede: '[ Open the Figma library · use the variables · sync via Code Connect ]',
    blocks: [
      {
        type: 'placeholder',
        label: '[ External-link list — Figma library, Code Connect docs ]',
      },
      {
        type: 'placeholder',
        variant: 'diagram',
        label: '[ Diagram — code ↔ Figma parity flow ]',
      },
    ],
  },
  '/getting-started/agents': {
    lede: '[ Point your agent at llms.txt · load the rule files · use the system prompt ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code block — system-prompt snippet ]',
      },
      {
        type: 'placeholder',
        label: '[ Download / copy buttons — llms.txt, rules.zip ]',
      },
    ],
  },
  '/components/inputs': {
    lede: '[ Interactive controls · per-component Storybook page below ]',
    blocks: [
      {
        type: 'row',
        blocks: [
          {
            variant: 'storybook',
            label: '[ Storybook embed — selected component ]',
          },
          { variant: 'tall', label: '[ Variant matrix · props table ]' },
        ],
      },
      { type: 'h2', text: '[ Per-component pages ]' },
      {
        type: 'placeholder',
        label: '[ Index — Button · Input · Select · Switch · Tabs ]',
      },
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — JSX usage example ]',
      },
    ],
  },
  '/components/containers': {
    lede: '[ Card · Dialog · Accordion · Alert ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Storybook embed ]',
      },
      {
        type: 'placeholder',
        label: '[ Composition patterns · slots / children ]',
      },
    ],
  },
  '/components/navigation': {
    lede: '[ DropdownMenu · (future) NavigationMenu · Breadcrumbs ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Storybook embed ]',
      },
    ],
  },
  '/components/display': {
    lede: '[ Badge · Avatar · Tooltip ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Storybook embed ]',
      },
    ],
  },
  '/components/primitives': {
    lede: '[ Low-level building blocks: Show / Hide · Slot ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — Show / Hide usage ]',
      },
      { type: 'placeholder', label: '[ API table ]' },
    ],
  },
  '/theming/density-modes': {
    lede: '[ Spacing density via data-density ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'tall',
        label:
          '[ Live demo — 6-mode grid · same component, different density ]',
      },
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — data-density attribute pattern ]',
      },
    ],
  },
  '/theming/overrides': {
    lede: '[ Re-point a token via CSS variable in your stylesheet ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — :root override pattern ]',
      },
      {
        type: 'placeholder',
        label: "[ Body — what's safe to override, what isn't ]",
      },
    ],
  },
  '/tools/nx-prefix': {
    lede: '[ Why everything is prefixed · how it composes with modifiers ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'code',
        label: "[ Code — examples · do / don't ]",
      },
      {
        type: 'placeholder',
        variant: 'table',
        label: '[ Table — prefix placement rules ]',
      },
    ],
  },
  '/tools/code-connect': {
    lede: '[ Mapping Figma components to code · maintaining .figma.ts ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — example .figma.ts ]',
      },
      {
        type: 'placeholder',
        variant: 'diagram',
        label: '[ Diagram — Figma ↔ code parity ]',
      },
    ],
  },
  '/tools/eslint': {
    lede: '[ @nexus_ds/eslint-plugin · canonical-spacing-steps · class conventions ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — install + config ]',
      },
      {
        type: 'placeholder',
        variant: 'table',
        label: '[ Table — rules · severity · what they flag ]',
      },
    ],
  },
  '/tools/audits': {
    lede: '[ figma-parity · APCA contrast · spacing-modes ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'table',
        label: '[ Table — audit · command · exit codes · what it catches ]',
      },
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — CI workflow snippet ]',
      },
    ],
  },
  '/tools/storybook': {
    lede: '[ Stories-as-tests · autodocs · base-variant grids ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'storybook',
        label: '[ Storybook embed — example component ]',
      },
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — story template ]',
      },
    ],
  },
  '/guidance/engineering': {
    lede: '[ Simplicity over cleverness · guard clauses · composition · ripple effect ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'table',
        label: '[ Table — principle · rule file · one-line summary ]',
      },
      {
        type: 'placeholder',
        label: '[ Cards — each rule from code-quality.md children ]',
      },
    ],
  },
  '/guidance/testing': {
    lede: '[ Stories are tests · vitest projects · APCA at the token layer ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'diagram',
        label: '[ Diagram — what runs where (storybook / unit / audits) ]',
      },
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — play function example ]',
      },
    ],
  },
  '/guidance/contribution': {
    lede: '[ Branch · PR title · review accounts · DoD ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'diagram',
        label: '[ Diagram — issue → branch → PR → review → merge ]',
      },
      {
        type: 'placeholder',
        variant: 'table',
        label: '[ Table — verdicts · review events · who posts ]',
      },
    ],
  },
  '/agents/llms-txt': {
    lede: '[ Point your model at one URL · machine-readable site map ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — llms.txt preview ]',
      },
      { type: 'placeholder', label: '[ Download · copy link ]' },
    ],
  },
  '/agents/rules-mirror': {
    lede: '[ All 17 rule files · readable on the web · always up to date ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'table',
        label: '[ Table — rule file · purpose · related ]',
      },
    ],
  },
  '/agents/authoring': {
    lede: '[ Copy-paste system prompts · authoring conventions · common pitfalls ]',
    blocks: [
      {
        type: 'placeholder',
        variant: 'code',
        label: '[ Code — system prompt template ]',
      },
      { type: 'placeholder', label: "[ Do / Don't list ]" },
    ],
  },
};
