// AUTO-GENERATED by apps/docs/scripts/generate-page-manifest.mjs — do not edit.
// Regenerate with `pnpm --filter @nexus_ds/docs generate:manifest`.

import type { ComponentType } from 'react';

/** Where a page's body comes from; `placeholder` pages render the registry wireframe. */
export type ManifestPageKind = 'mdx' | 'component' | 'placeholder';

// eslint-disable-next-line @nexus_ds/no-render-prop-types -- `default: ComponentType` is the shape of a lazily-imported page module, not a component-as-prop.
export type ManifestPageLoader = () => Promise<{ default: ComponentType }>;

export type ManifestPage = {
  /** Route path, e.g. `/foundations/color`. */
  route: string;
  slug: string;
  label: string;
  /** Position within the section, zero-based. */
  order: number;
  /** Non-interactive labels rendered under this page in the left rail. */
  nested?: readonly string[];
  kind: ManifestPageKind;
  /** Source file relative to `apps/docs`; `null` for placeholder pages. */
  file: string | null;
  /** Lazy module loader; `null` for placeholder pages. */
  load: ManifestPageLoader | null;
};

export type ManifestSection = {
  slug: string;
  title: string;
  href: string;
  /** Position in the top-level nav, zero-based. */
  order: number;
  pages: readonly ManifestPage[];
};

export const PAGE_MANIFEST: readonly ManifestSection[] = [
  {
    slug: 'getting-started',
    title: 'Getting Started',
    href: '/getting-started',
    order: 0,
    pages: [
      {
        route: '/getting-started/install',
        slug: 'install',
        label: 'Install',
        order: 0,
        kind: 'mdx',
        file: 'content/getting-started/install.mdx',
        load: () => import('../../content/getting-started/install.mdx'),
      },
      {
        route: '/getting-started/theme-setup',
        slug: 'theme-setup',
        label: 'Theme setup',
        order: 1,
        kind: 'mdx',
        file: 'content/getting-started/theme-setup.mdx',
        load: () => import('../../content/getting-started/theme-setup.mdx'),
      },
      {
        route: '/getting-started/first-component',
        slug: 'first-component',
        label: 'Your first component',
        order: 2,
        kind: 'placeholder',
        file: null,
        load: null,
      },
      {
        route: '/getting-started/designers',
        slug: 'designers',
        label: 'For designers',
        order: 3,
        kind: 'placeholder',
        file: null,
        load: null,
      },
      {
        route: '/getting-started/agents',
        slug: 'agents',
        label: 'For AI agents',
        order: 4,
        kind: 'placeholder',
        file: null,
        load: null,
      },
    ],
  },
  {
    slug: 'foundations',
    title: 'Foundations',
    href: '/foundations',
    order: 1,
    pages: [
      {
        route: '/foundations/color',
        slug: 'color',
        label: 'Color',
        order: 0,
        kind: 'component',
        file: 'app/_pages/foundations/color.tsx',
        nested: [
          'How color works',
          'Palette & shades',
          'Surfaces',
          'Accessibility',
        ],
        load: () => import('../_pages/foundations/color'),
      },
      {
        route: '/foundations/typography',
        slug: 'typography',
        label: 'Typography',
        order: 1,
        kind: 'component',
        file: 'app/_pages/foundations/typography.tsx',
        load: () => import('../_pages/foundations/typography'),
      },
      {
        route: '/foundations/spacing',
        slug: 'spacing',
        label: 'Spacing',
        order: 2,
        kind: 'component',
        file: 'app/_pages/foundations/spacing.tsx',
        load: () => import('../_pages/foundations/spacing'),
      },
      {
        route: '/foundations/radius',
        slug: 'radius',
        label: 'Radius · Borders · Shadows',
        order: 3,
        kind: 'component',
        file: 'app/_pages/foundations/radius.tsx',
        load: () => import('../_pages/foundations/radius'),
      },
      {
        route: '/foundations/layering',
        slug: 'layering',
        label: 'Layering',
        order: 4,
        kind: 'component',
        file: 'app/_pages/foundations/layering.tsx',
        load: () => import('../_pages/foundations/layering'),
      },
      {
        route: '/foundations/responsive',
        slug: 'responsive',
        label: 'Responsive',
        order: 5,
        kind: 'component',
        file: 'app/_pages/foundations/responsive.tsx',
        load: () => import('../_pages/foundations/responsive'),
      },
    ],
  },
  {
    slug: 'components',
    title: 'Components',
    href: '/components',
    order: 2,
    pages: [
      {
        route: '/components/inputs',
        slug: 'inputs',
        label: 'Inputs',
        order: 0,
        kind: 'placeholder',
        file: null,
        nested: ['Button', 'Input', 'Select', 'Switch', 'Tabs'],
        load: null,
      },
      {
        route: '/components/containers',
        slug: 'containers',
        label: 'Containers',
        order: 1,
        kind: 'placeholder',
        file: null,
        nested: ['Card', 'Dialog', 'Accordion', 'Alert'],
        load: null,
      },
      {
        route: '/components/navigation',
        slug: 'navigation',
        label: 'Navigation',
        order: 2,
        kind: 'placeholder',
        file: null,
        nested: ['DropdownMenu'],
        load: null,
      },
      {
        route: '/components/display',
        slug: 'display',
        label: 'Display',
        order: 3,
        kind: 'placeholder',
        file: null,
        nested: ['Badge', 'Avatar', 'Tooltip'],
        load: null,
      },
      {
        route: '/components/primitives',
        slug: 'primitives',
        label: 'Primitives',
        order: 4,
        kind: 'placeholder',
        file: null,
        nested: ['Show / Hide', 'Slot'],
        load: null,
      },
    ],
  },
  {
    slug: 'theming',
    title: 'Theming',
    href: '/theming',
    order: 3,
    pages: [
      {
        route: '/theming/appearance',
        slug: 'appearance',
        label: 'Appearance',
        order: 0,
        kind: 'mdx',
        file: 'content/theming/appearance.mdx',
        load: () => import('../../content/theming/appearance.mdx'),
      },
      {
        route: '/theming/multi-brand',
        slug: 'multi-brand',
        label: 'Multi-brand',
        order: 1,
        kind: 'component',
        file: 'app/_pages/theming/multi-brand.tsx',
        load: () => import('../_pages/theming/multi-brand'),
      },
      {
        route: '/theming/density-modes',
        slug: 'density-modes',
        label: 'Density modes',
        order: 2,
        kind: 'placeholder',
        file: null,
        load: null,
      },
      {
        route: '/theming/overrides',
        slug: 'overrides',
        label: 'Consumer overrides',
        order: 3,
        kind: 'placeholder',
        file: null,
        load: null,
      },
    ],
  },
  {
    slug: 'tools',
    title: 'Tools',
    href: '/tools',
    order: 4,
    pages: [
      {
        route: '/tools/nx-prefix',
        slug: 'nx-prefix',
        label: 'nx: prefix (Tailwind)',
        order: 0,
        kind: 'placeholder',
        file: null,
        load: null,
      },
      {
        route: '/tools/code-connect',
        slug: 'code-connect',
        label: 'Figma Code Connect',
        order: 1,
        kind: 'placeholder',
        file: null,
        load: null,
      },
      {
        route: '/tools/eslint',
        slug: 'eslint',
        label: 'ESLint plugin',
        order: 2,
        kind: 'placeholder',
        file: null,
        load: null,
      },
      {
        route: '/tools/audits',
        slug: 'audits',
        label: 'Token audits',
        order: 3,
        kind: 'placeholder',
        file: null,
        load: null,
      },
      {
        route: '/tools/storybook',
        slug: 'storybook',
        label: 'Storybook',
        order: 4,
        kind: 'placeholder',
        file: null,
        load: null,
      },
    ],
  },
  {
    slug: 'guidance',
    title: 'Guidance',
    href: '/guidance',
    order: 5,
    pages: [
      {
        route: '/guidance/engineering',
        slug: 'engineering',
        label: 'Engineering principles',
        order: 0,
        kind: 'placeholder',
        file: null,
        load: null,
      },
      {
        route: '/guidance/testing',
        slug: 'testing',
        label: 'Testing model',
        order: 1,
        kind: 'placeholder',
        file: null,
        load: null,
      },
      {
        route: '/guidance/contribution',
        slug: 'contribution',
        label: 'Contribution workflow',
        order: 2,
        kind: 'placeholder',
        file: null,
        load: null,
      },
    ],
  },
  {
    slug: 'agents',
    title: 'For AI agents',
    href: '/agents',
    order: 6,
    pages: [
      {
        route: '/agents/llms-txt',
        slug: 'llms-txt',
        label: 'llms.txt',
        order: 0,
        kind: 'placeholder',
        file: null,
        load: null,
      },
      {
        route: '/agents/rules-mirror',
        slug: 'rules-mirror',
        label: 'Rules mirror',
        order: 1,
        kind: 'placeholder',
        file: null,
        load: null,
      },
      {
        route: '/agents/authoring',
        slug: 'authoring',
        label: 'Agent authoring',
        order: 2,
        kind: 'placeholder',
        file: null,
        load: null,
      },
    ],
  },
];
