// AUTO-GENERATED by apps/docs/scripts/generate-page-manifest.mjs — do not edit.
// Regenerate with `pnpm --filter @nexus_ds/docs generate:manifest`.

export type ManifestPage = {
  /** Route path, e.g. `/foundations/color`. */
  route: string;
  slug: string;
  label: string;
  /** Components this group page covers, listed under it in the left rail. */
  components?: readonly string[];
  /** Non-interactive headings listed under this page in the left rail. */
  nested?: readonly string[];
} & (
  | {
      kind: 'mdx' | 'component';
      /** Source file relative to `apps/docs`; the module is `PAGE_LOADERS[route]`. */
      file: string;
    }
  | {
      /** No page file yet; the body is `PAGE_WIREFRAMES[route]`. */
      kind: 'placeholder';
      file: null;
    }
);

export type ManifestSection = {
  slug: string;
  title: string;
  href: string;
  /** What the section is counted in on the home page. Defaults to pages. */
  unit?: 'components';
  pages: readonly ManifestPage[];
};

/** Every docs page, in nav order. Serializable — safe to import from a client component. */
export const PAGE_MANIFEST: readonly ManifestSection[] = [
  {
    slug: 'getting-started',
    title: 'Getting Started',
    href: '/getting-started',
    pages: [
      {
        route: '/getting-started/install',
        slug: 'install',
        label: 'Install',
        kind: 'mdx',
        file: 'content/getting-started/install.mdx',
      },
      {
        route: '/getting-started/theme-setup',
        slug: 'theme-setup',
        label: 'Theme setup',
        kind: 'mdx',
        file: 'content/getting-started/theme-setup.mdx',
      },
      {
        route: '/getting-started/first-component',
        slug: 'first-component',
        label: 'Your first component',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/getting-started/designers',
        slug: 'designers',
        label: 'For designers',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/getting-started/agents',
        slug: 'agents',
        label: 'For AI agents',
        kind: 'placeholder',
        file: null,
      },
    ],
  },
  {
    slug: 'foundations',
    title: 'Foundations',
    href: '/foundations',
    pages: [
      {
        route: '/foundations/color',
        slug: 'color',
        label: 'Color',
        nested: [
          'How color works',
          'Palette & shades',
          'Surfaces',
          'Accessibility',
        ],
        kind: 'component',
        file: 'app/_pages/foundations/color.tsx',
      },
      {
        route: '/foundations/typography',
        slug: 'typography',
        label: 'Typography',
        kind: 'component',
        file: 'app/_pages/foundations/typography.tsx',
      },
      {
        route: '/foundations/spacing',
        slug: 'spacing',
        label: 'Spacing',
        kind: 'component',
        file: 'app/_pages/foundations/spacing.tsx',
      },
      {
        route: '/foundations/radius',
        slug: 'radius',
        label: 'Radius · Borders · Shadows',
        kind: 'component',
        file: 'app/_pages/foundations/radius.tsx',
      },
      {
        route: '/foundations/layering',
        slug: 'layering',
        label: 'Layering',
        kind: 'component',
        file: 'app/_pages/foundations/layering.tsx',
      },
      {
        route: '/foundations/responsive',
        slug: 'responsive',
        label: 'Responsive',
        kind: 'component',
        file: 'app/_pages/foundations/responsive.tsx',
      },
    ],
  },
  {
    slug: 'components',
    title: 'Components',
    href: '/components',
    unit: 'components',
    pages: [
      {
        route: '/components/inputs',
        slug: 'inputs',
        label: 'Inputs',
        components: ['Button', 'Input', 'Select', 'Switch', 'Tabs'],
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/containers',
        slug: 'containers',
        label: 'Containers',
        components: ['Card', 'Dialog', 'Accordion', 'Alert'],
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/navigation',
        slug: 'navigation',
        label: 'Navigation',
        components: ['DropdownMenu'],
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/display',
        slug: 'display',
        label: 'Display',
        components: ['Badge', 'Avatar', 'Tooltip'],
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/components/primitives',
        slug: 'primitives',
        label: 'Primitives',
        components: ['Show / Hide', 'Slot'],
        kind: 'placeholder',
        file: null,
      },
    ],
  },
  {
    slug: 'theming',
    title: 'Theming',
    href: '/theming',
    pages: [
      {
        route: '/theming/appearance',
        slug: 'appearance',
        label: 'Appearance',
        kind: 'mdx',
        file: 'content/theming/appearance.mdx',
      },
      {
        route: '/theming/multi-brand',
        slug: 'multi-brand',
        label: 'Multi-brand',
        kind: 'component',
        file: 'app/_pages/theming/multi-brand.tsx',
      },
      {
        route: '/theming/density-modes',
        slug: 'density-modes',
        label: 'Density modes',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/theming/overrides',
        slug: 'overrides',
        label: 'Consumer overrides',
        kind: 'placeholder',
        file: null,
      },
    ],
  },
  {
    slug: 'tools',
    title: 'Tools',
    href: '/tools',
    pages: [
      {
        route: '/tools/nx-prefix',
        slug: 'nx-prefix',
        label: 'nx: prefix (Tailwind)',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/tools/code-connect',
        slug: 'code-connect',
        label: 'Figma Code Connect',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/tools/eslint',
        slug: 'eslint',
        label: 'ESLint plugin',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/tools/audits',
        slug: 'audits',
        label: 'Token audits',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/tools/storybook',
        slug: 'storybook',
        label: 'Storybook',
        kind: 'placeholder',
        file: null,
      },
    ],
  },
  {
    slug: 'guidance',
    title: 'Guidance',
    href: '/guidance',
    pages: [
      {
        route: '/guidance/engineering',
        slug: 'engineering',
        label: 'Engineering principles',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/guidance/testing',
        slug: 'testing',
        label: 'Testing model',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/guidance/contribution',
        slug: 'contribution',
        label: 'Contribution workflow',
        kind: 'placeholder',
        file: null,
      },
    ],
  },
  {
    slug: 'agents',
    title: 'For AI agents',
    href: '/agents',
    pages: [
      {
        route: '/agents/llms-txt',
        slug: 'llms-txt',
        label: 'llms.txt',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/agents/rules-mirror',
        slug: 'rules-mirror',
        label: 'Rules mirror',
        kind: 'placeholder',
        file: null,
      },
      {
        route: '/agents/authoring',
        slug: 'authoring',
        label: 'Agent authoring',
        kind: 'placeholder',
        file: null,
      },
    ],
  },
];
