// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./demo.client";

export const source = "'use client';\n\nimport { Button } from '@/components/button/button';\nimport { ButtonGroup } from '@/components/button-group/button-group';\n\nexport default function ButtonGroupDemo() {\n  return (\n    <ButtonGroup>\n      <Button variant=\"outline\">Day</Button>\n      <Button variant=\"outline\">Week</Button>\n      <Button variant=\"outline\">Month</Button>\n    </ButtonGroup>\n  );\n}\n";
