// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./sizes.client";

export const source = "'use client';\n\nimport { Button } from '@/components/button/button';\nimport {\n  ButtonGroup,\n  ButtonGroupText,\n} from '@/components/button-group/button-group';\n\nexport default function ButtonGroupSizes() {\n  return (\n    <div className=\"nx:flex nx:flex-col nx:items-start nx:gap-4\">\n      <ButtonGroup size=\"sm\">\n        <ButtonGroupText>Small</ButtonGroupText>\n        <Button variant=\"outline\">Day</Button>\n        <Button variant=\"outline\">Week</Button>\n      </ButtonGroup>\n      <ButtonGroup size=\"default\">\n        <ButtonGroupText>Default</ButtonGroupText>\n        <Button variant=\"outline\">Day</Button>\n        <Button variant=\"outline\">Week</Button>\n      </ButtonGroup>\n      <ButtonGroup size=\"lg\">\n        <ButtonGroupText>Large</ButtonGroupText>\n        <Button variant=\"outline\">Day</Button>\n        <Button variant=\"outline\">Week</Button>\n      </ButtonGroup>\n    </div>\n  );\n}\n";
