// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./vertical.client";

export const source = "'use client';\n\nimport { Button } from '@/components/button/button';\nimport { ButtonGroup } from '@/components/button-group/button-group';\n\nexport default function ButtonGroupVertical() {\n  return (\n    <ButtonGroup orientation=\"vertical\" size=\"sm\">\n      <Button variant=\"outline\">Top</Button>\n      <Button variant=\"outline\">Middle</Button>\n      <Button variant=\"outline\">Bottom</Button>\n    </ButtonGroup>\n  );\n}\n";
