// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./with-text.client";

export const source = "'use client';\n\nimport { Button } from '@/components/button/button';\nimport {\n  ButtonGroup,\n  ButtonGroupText,\n} from '@/components/button-group/button-group';\n\nexport default function ButtonGroupWithText() {\n  return (\n    <ButtonGroup>\n      <ButtonGroupText>https://</ButtonGroupText>\n      <Button variant=\"outline\">nexus.dev</Button>\n    </ButtonGroup>\n  );\n}\n";
