// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./with-separator.client";

export const source = "'use client';\n\nimport {\n  IconBold,\n  IconItalic,\n  IconLink,\n  IconUnderline,\n} from '@tabler/icons-react';\n\nimport { Button } from '@/components/button/button';\nimport {\n  ButtonGroup,\n  ButtonGroupSeparator,\n} from '@/components/button-group/button-group';\n\nexport default function ButtonGroupWithSeparator() {\n  return (\n    <ButtonGroup>\n      <Button variant=\"ghost\" size=\"icon\" aria-label=\"Bold\">\n        <IconBold />\n      </Button>\n      <Button variant=\"ghost\" size=\"icon\" aria-label=\"Italic\">\n        <IconItalic />\n      </Button>\n      <Button variant=\"ghost\" size=\"icon\" aria-label=\"Underline\">\n        <IconUnderline />\n      </Button>\n      <ButtonGroupSeparator />\n      <Button variant=\"ghost\" size=\"icon\" aria-label=\"Add link\">\n        <IconLink />\n      </Button>\n    </ButtonGroup>\n  );\n}\n";
