// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./demo.client";

export const source = "import { Button } from '@nexus_ds/react';\n\nexport default function ButtonDemo() {\n  return <Button>Button</Button>;\n}\n";
