// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./disabled.client";

export const source = "'use client';\n\nimport { Button } from '@/components/button/button';\n\nexport default function ButtonDisabled() {\n  return (\n    <div className=\"nx:flex nx:flex-wrap nx:items-center nx:gap-2\">\n      <Button variant=\"default\" disabled>\n        Default\n      </Button>\n      <Button variant=\"secondary\" disabled>\n        Secondary\n      </Button>\n      <Button variant=\"error\" disabled>\n        Error\n      </Button>\n      <Button variant=\"destructive\" disabled>\n        Destructive\n      </Button>\n      <Button variant=\"outline\" disabled>\n        Outline\n      </Button>\n      <Button variant=\"dashed\" disabled>\n        Dashed\n      </Button>\n      <Button variant=\"ghost\" disabled>\n        Ghost\n      </Button>\n      <Button variant=\"link\" disabled>\n        Link\n      </Button>\n    </div>\n  );\n}\n";
