// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./sizes.client";

export const source = "'use client';\n\nimport { IconStar } from '@tabler/icons-react';\n\nimport { Button } from '@/components/button/button';\n\nexport default function ButtonSizes() {\n  return (\n    <div className=\"nx:flex nx:flex-wrap nx:items-center nx:gap-2\">\n      <Button size=\"sm\">Small</Button>\n      <Button size=\"default\">Default</Button>\n      <Button size=\"lg\">Large</Button>\n      <Button size=\"icon-sm\" aria-label=\"Favorite (small)\">\n        <IconStar />\n      </Button>\n      <Button size=\"icon\" aria-label=\"Favorite\">\n        <IconStar />\n      </Button>\n      <Button size=\"icon-lg\" aria-label=\"Favorite (large)\">\n        <IconStar />\n      </Button>\n    </div>\n  );\n}\n";
