// Generated by apps/docs/scripts/generate-demo-index.mjs — do not edit.
// Run `pnpm --filter @nexus_ds/docs generate:demos` to regenerate.

export { Component } from "./with-icon.client";

export const source = "'use client';\n\nimport { IconArrowRight, IconRocket } from '@tabler/icons-react';\n\nimport { Button } from '@/components/button/button';\n\nexport default function ButtonWithIcon() {\n  return (\n    <div className=\"nx:flex nx:flex-wrap nx:items-center nx:gap-2\">\n      <Button startIcon={<IconRocket />}>Launch</Button>\n      <Button variant=\"outline\" endIcon={<IconArrowRight />}>\n        Continue\n      </Button>\n    </div>\n  );\n}\n";
